#!/bin/bash

echo 'Generating spawn table'

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

source /home/cslics/mambaforge/bin/activate cslics
for remote in $(cat $DIR/../rrap-downloader/remotes); do
  python3 $DIR/coral_spawn_counter/spawn_table.py $remote &
done

wait 

echo 'Done'
